CREATE DATABASE QuanLyCuaHang DEFAULT CHARACTER
SET utf8 DEFAULT COLLATE utf8_general_ci;

USE QuanLyCuaHang;

CREATE TABLE TYPE_OF_PRODUCT (
	CODE_TYPE VARCHAR (20) NOT NULL PRIMARY KEY,
	NAME VARCHAR (20) NOT NULL,
	UNIT VARCHAR (10) NOT NULL
);

CREATE TABLE SUPPLIER (
	CODE_SUPPLIER VARCHAR (20) NOT NULL PRIMARY KEY,
	NAME VARCHAR (50) NOT NULL,
	COUNTRY VARCHAR (20) NOT NULL
);

CREATE TABLE STAFFS (
	CODE_STAFF VARCHAR (20) NOT NULL PRIMARY KEY,
	NAME VARCHAR (50) NOT NULL,
	DATE_OF_BIRTH DATE,
	PHONE_NUMBER VARCHAR (11),
	IMAGE VARCHAR (512) CHARACTER
SET 'ascii' COLLATE 'ascii_general_ci' NOT NULL
);

CREATE TABLE ROLL_CALL (
	CODE_STAFF VARCHAR (20) NOT NULL,
	DATE DATE,
	STATUS INT
);

CREATE TABLE PRODUCTS (
	CODE_PRODUCT VARCHAR (20) NOT NULL PRIMARY KEY,
	NAME VARCHAR (50) NOT NULL,
	CODE_SUPPLIER VARCHAR (20) NOT NULL,
	CODE_TYPE VARCHAR (20) NOT NULL,
	IMAGE VARCHAR (512) CHARACTER
SET 'ascii' COLLATE 'ascii_general_ci' NOT NULL,
 FOREIGN KEY (CODE_SUPPLIER) REFERENCES SUPPLIER (CODE_SUPPLIER),
 FOREIGN KEY (CODE_TYPE) REFERENCES TYPE_OF_PRODUCT (CODE_TYPE)
);

CREATE TABLE STATUS (
	CODE_PRODUCT VARCHAR (20) NOT NULL PRIMARY KEY,
	QUANTITY INT NOT NULL,
	PRICE INT NOT NULL,
	FOREIGN KEY (CODE_PRODUCT) REFERENCES PRODUCTS (CODE_PRODUCT)
);

CREATE TABLE INPUT_BILL (
	CODE_INPUT_BILL VARCHAR (20) NOT NULL PRIMARY KEY,
	CODE_STAFF VARCHAR (20) NOT NULL,	
	DATE DATE,
	FOREIGN KEY (CODE_STAFF) REFERENCES STAFFS (CODE_STAFF)
);


CREATE TABLE LIST_ITEMS (
	CODE_BILL VARCHAR (20) NOT NULL,
	CODE_PRODUCT VARCHAR (20) NOT NULL,
	CODE_SUPPLIER VARCHAR (20) NOT NULL,
	CODE_TYPE VARCHAR (20) NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE INT NOT NULL,
	FOREIGN KEY (CODE_PRODUCT) REFERENCES PRODUCTS (CODE_PRODUCT),
	FOREIGN KEY (CODE_SUPPLIER) REFERENCES SUPPLIER (CODE_SUPPLIER),
	FOREIGN KEY (CODE_TYPE) REFERENCES TYPE_OF_PRODUCT (CODE_TYPE)
);

CREATE TABLE OUTPUT_BILL (
	CODE_OUTPUT_BILL VARCHAR (20) NOT NULL PRIMARY KEY,
	CODE_STAFF VARCHAR (20) NOT NULL,
	NAME_CUSTOMMER VARCHAR (50) NOT NULL,
	DATE DATE,
	FOREIGN KEY (CODE_STAFF) REFERENCES STAFFS (CODE_STAFF)
);

