/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.Manage_Product_CONTROLER;
import Model.Type_Of_Product;
import Model.Supplier;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hiep
 */
public class Delete_pst_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Delete_pst_GUI
     */
    Manage_Product_CONTROLER control = new Manage_Product_CONTROLER();
    private int selected = 0;
    Thread t = null;

    public Delete_pst_GUI() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Delete");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_delete = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Chọn thứ gì đó để xóa");

        jComboBox_delete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn thứ gì đó","Sản phẩm", "Nhà sản xuất", "Loại sản phẩm" }));
        jComboBox_delete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_deleteItemStateChanged(evt);
            }
        });
        jComboBox_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_deleteActionPerformed(evt);
            }
        });

        jTable_display.setModel(new javax.swing.table.DefaultTableModel());
        jTable_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jComboBox_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_deleteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox_deleteActionPerformed

    private void jTable_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_displayMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        // int column = source.columnAtPoint(evt.getPoint());
        // "Mã thiết bị", "Tên thiết bị", "Mã NSX", "Mã loại","Giá thành"
        String id = source.getModel().getValueAt(row, 0) + "";
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (this.selected == 1) {
                Product temp = new Product();
                temp.setCode_product(id);
                temp.delete();
                JOptionPane.showMessageDialog(null, "Xóa thành công", "congratulations", JOptionPane.INFORMATION_MESSAGE);

            } else if (this.selected == 2) {
                Supplier temp = new Supplier();
                temp.setCode_Supplier(id);
                temp.delete();
                JOptionPane.showMessageDialog(null, "Xóa thành công", "congratulations", JOptionPane.INFORMATION_MESSAGE);

            } else if (this.selected == 3) {
                Type_Of_Product temp = new Type_Of_Product();
                temp.setCodeType(id);
                temp.delete();
                JOptionPane.showMessageDialog(null, "Xóa thành công", "congratulations", JOptionPane.INFORMATION_MESSAGE);

            }

        } else {
            // no option
        }
    }//GEN-LAST:event_jTable_displayMouseClicked

    private void jComboBox_deleteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_deleteItemStateChanged
        // TODO add your handling code here:
        this.selected = jComboBox_delete.getSelectedIndex();
        switch (this.selected) {
            case 1: {
                display_Prod();
                break;
            }
            case 2: {
                display_sup();
                break;
            }
            case 3: {
                display_type();
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_jComboBox_deleteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_pst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_pst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_pst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_pst_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_pst_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display;
    // End of variables declaration//GEN-END:variables

    public void display_Prod() {
        Object[][] data = {};
        String[] columnNames = {"Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Nhà sản xuất"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable_display.setModel(model);

        ArrayList<Product> list = control.get_List_Product();
        DefaultTableModel model_ = (DefaultTableModel) jTable_display.getModel();
        model_.setRowCount(0);
        for (Product temp : list) {
            Supplier sup = new Supplier();
            Type_Of_Product type = new Type_Of_Product();
            sup.getDetail(temp.getCode_supplier());
            type.getDetail(temp.getCode_type());
            model_.addRow(new Object[]{temp.getCode_product(), temp.getName(), type.getNameType(), sup.getName_Supplier()});
        }
    }

    public void display_sup() {
        Object[][] data = {};
        String[] columnNames = {"Mã NSX", "Tên NSX", "Quốc gia"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable_display.setModel(model);

        ArrayList<Supplier> list = control.get_List_Supplier();
        DefaultTableModel model_ = (DefaultTableModel) jTable_display.getModel();
        model_.setRowCount(0);
        for (Supplier temp : list) {
            model_.addRow(new Object[]{temp.getCode_Supplier(), temp.getName_Supplier(), temp.getCountry()});
        }
    }

    public void display_type() {
        Object[][] data = {};
        String[] columnNames = {"Mã Loại", "Tên Loại", "Đơn vị tính"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable_display.setModel(model);

        ArrayList<Type_Of_Product> list = control.get_List_Type();
        DefaultTableModel model_ = (DefaultTableModel) jTable_display.getModel();
        model_.setRowCount(0);
        for (Type_Of_Product temp : list) {
            model_.addRow(new Object[]{temp.getCodeType(), temp.getNameType(), temp.getUnit()});
        }
    }

}
